name: ui_extension_examples
description: Examples for ui_extension.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.1.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_animate: 4.3.0
  get: ^4.6.5
  nested: ^1.0.0
  styled_widget: ^0.4.1
  ui_extension:
    path: ../
    
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0


flutter:
  uses-material-design: true
