name: ui_extension
description: Extend your ui with smart and easy to use widgets and extensions.
version: 0.0.1
homepage: https://www.branvier.com

environment:
  sdk: ">=2.17.0 <4.0.0"

dependencies:
  animated_value: ^0.0.1
  nested: ^1.0.0
  flutter:
    sdk: flutter
  gap: ^3.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
